# Generated by Django 5.2.4 on 2025-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_file_file_folder_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='user_files/'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
