# Generated by Django 5.2.4 on 2025-09-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_folder_file_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_folder',
            new_name='parent',
        ),
    ]
