# Generated by Django 5.2.4 on 2025-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_parent_folder_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_limit',
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.AddField(
            model_name='profile',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
