# Generated by Django 5.2.4 on 2025-09-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_file_deleted_at_file_in_trash_folder_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
