# Generated by Django 5.2.4 on 2025-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_file_is_favorite_folder_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
