# Generated by Django 5.2 on 2025-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_file_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
