# Generated by Django 5.2.4 on 2025-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_file_thumbnail_file_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
