# Generated by Django 5.2.4 on 2025-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_file_share_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
