# Generated by Django 5.2.4 on 2025-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_file_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='iv',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_vault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='vault_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
