# Generated by Django 5.2.4 on 2025-11-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_file_iv_folder_is_vault_folder_vault_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_versions/')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.file')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
