# Generated by Django 5.2.4 on 2025-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fileversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ai_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
