# Generated by Django 5.2.4 on 2025-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_file_ai_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ai_tags',
        ),
        migrations.AddField(
            model_name='file',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
