# Generated by Django 5.2.4 on 2025-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_file_ai_tags_file_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
