# Generated by Django 5.2.4 on 2025-11-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_file_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
